// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDya3Wv713DPt8v3cxgRF1e87dTweumXgo',
    appId: '1:980927911099:web:509853146e5d584213859e',
    messagingSenderId: '980927911099',
    projectId: 'chat-app-99b46',
    authDomain: 'chat-app-99b46.firebaseapp.com',
    storageBucket: 'chat-app-99b46.firebasestorage.app',
    measurementId: 'G-Y9FKL16V8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPl6Qm8dB1kZtS5KMK_fq6XwYfwY5yQ08',
    appId: '1:980927911099:android:b4df803809ecb1ae13859e',
    messagingSenderId: '980927911099',
    projectId: 'chat-app-99b46',
    storageBucket: 'chat-app-99b46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0XpPyupEGGcIrAeTSmztbpuBmZSOQn38',
    appId: '1:980927911099:ios:2d434db3715cbbb513859e',
    messagingSenderId: '980927911099',
    projectId: 'chat-app-99b46',
    storageBucket: 'chat-app-99b46.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0XpPyupEGGcIrAeTSmztbpuBmZSOQn38',
    appId: '1:980927911099:ios:2d434db3715cbbb513859e',
    messagingSenderId: '980927911099',
    projectId: 'chat-app-99b46',
    storageBucket: 'chat-app-99b46.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDya3Wv713DPt8v3cxgRF1e87dTweumXgo',
    appId: '1:980927911099:web:d9215f671c355eba13859e',
    messagingSenderId: '980927911099',
    projectId: 'chat-app-99b46',
    authDomain: 'chat-app-99b46.firebaseapp.com',
    storageBucket: 'chat-app-99b46.firebasestorage.app',
    measurementId: 'G-WNJTYXRTHP',
  );
}
